### ISSUE TITLE
please add tags for releases

### ISSUE THREAD

**Issue by pravi** [jonschlinkert/union-value#1]
We take github tarballs to create debian package and missing tags makes it hard to find the commits corresponding to release.

**Comment by jonschlinkert** [comment]
Please ask for something specific, like "please tag release number x.x.x". We tag all releases currently.

**Comment by pravi** [comment]
This repo did not have any tags. See screenshot. When tags for a specific release is missing, I ask for that release.

![screenshot from 2016-10-28 12-32-12](https://cloud.githubusercontent.com/assets/708222/19804190/764d63ec-9d2a-11e6-8f73-f8ab69de2c6e.png)

**Comment by jonschlinkert** [comment]
sorry, that's not what I meant. this repository did not have any tags. But you implied that you wanted me to add a tag for all of the releases on this repository, which doesn't make sense. Or were you asking me to tag all of my projects? In which case your request goes beyond the scope of this repository. Since we tag all releases now, and have done so for quite a while, you will need to create an issue on any projects that are missing a tag - I just ask that you please be specific.

**Comment by pravi** [comment]
Well, this issue was opened for union-value project and meant for this project only. I thought that was clear. I don't understand what extra detail was needed. I open issue only if a specific project is missing tags and looking at the issue url you can see which project it is referring to. If you want I can mention name of the project and version too in future issues.

**Comment by jonschlinkert** [comment]
> If you want I can mention name of the project and version too in future issues.

No, name isn't necessary. Version is fine, thanks.
